// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerTraderExam.Infrastructure.Persistence;

#nullable disable

namespace PowerTraderExam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518074851_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CandidateNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdCard")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("OrgName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "CandidateNo")
                        .IsUnique();

                    b.HasIndex("BatchId", "SyncStatus");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.CandidateSyncLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "ServerId")
                        .IsUnique();

                    b.ToTable("candidate_sync_logs", (string)null);
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ExamBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.ToTable("exam_batches", (string)null);
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ExamScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AnswerUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailJson")
                        .HasColumnType("longtext");

                    b.Property<int>("PushStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PushedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SourceServerId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "Subject")
                        .IsUnique();

                    b.HasIndex("PushStatus", "ScoredAt");

                    b.ToTable("exam_scores", (string)null);
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ExamServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("exam_servers", (string)null);
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ScorePushLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<long>("ExamScoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestBody")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("longtext");

                    b.Property<string>("SignHeader")
                        .HasColumnType("longtext");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TimestampHeader")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExamScoreId");

                    b.ToTable("score_push_logs", (string)null);
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("PowerTraderExam.Domain.Entities.ExamBatch", "Batch")
                        .WithMany("Candidates")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.CandidateSyncLog", b =>
                {
                    b.HasOne("PowerTraderExam.Domain.Entities.Candidate", "Candidate")
                        .WithMany("SyncLogs")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ExamScore", b =>
                {
                    b.HasOne("PowerTraderExam.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Scores")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ScorePushLog", b =>
                {
                    b.HasOne("PowerTraderExam.Domain.Entities.ExamScore", "ExamScore")
                        .WithMany("PushLogs")
                        .HasForeignKey("ExamScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamScore");
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("Scores");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ExamBatch", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("PowerTraderExam.Domain.Entities.ExamScore", b =>
                {
                    b.Navigation("PushLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
